import { useState } from 'react';
import { Settings, ShieldCheck, TrendingUp, AlertCircle, Printer } from 'lucide-react';
import { useProgress } from '../context/ProgressContext';

export default function ParentDashboard() {
  const { progress } = useProgress();
  const [showPrintPreview, setShowPrintPreview] = useState(false);

  const generateProblems = () => {
    const problems = [];
    for (let i = 0; i < 20; i++) {
      const a = Math.floor(Math.random() * 50) + 1;
      const b = Math.floor(Math.random() * 50) + 1;
      const op = Math.random() > 0.5 ? '+' : '-';
      const valA = op === '-' && b > a ? b : a;
      const valB = op === '-' && b > a ? a : b;
      problems.push({
        id: i + 1,
        question: `${valA} ${op} ${valB} = `,
        answer: op === '+' ? valA + valB : valA - valB
      });
    }
    return problems;
  };

  const problems = generateProblems();

  return (
    <div className="max-w-4xl mx-auto space-y-8">
      {/* Hidden Printable Area - Only visible during print */}
      <div className="hidden print:block print:p-8 print:text-black bg-white">
        <div className="text-center mb-8 border-b-2 border-black pb-4">
          <h1 className="text-3xl font-bold">Abacus Mental Math Worksheet</h1>
          <p className="text-lg">Student Name: ____________________ Date: __________</p>
        </div>
        <div className="grid grid-cols-2 gap-x-12 gap-y-6">
          {problems.map(p => (
            <div key={p.id} className="text-2xl font-mono border-b border-gray-300 pb-2">
              {p.id}. {p.question} __________
            </div>
          ))}
        </div>
        <div className="mt-12 text-sm text-gray-500 italic text-center">
          Generated by Abacus Mind Learning App - Keep Practicing!
        </div>
      </div>

      {/* Screen Interface (Hidden during print) */}
      <div className="print:hidden">
        <div className="flex items-center justify-between">
          <div className="flex-1">
            <h2 className="font-fredoka text-3xl text-text-dark">Parental Portal</h2>
            <p className="text-text-medium">Monitor progress and manage your child's learning experience.</p>
          </div>
          <div className="flex items-center gap-2 bg-green-50 text-accent-green px-3 py-1 rounded-full text-sm font-bold border border-green-200">
            <ShieldCheck className="w-4 h-4" /> 
            COPPA Compliant
          </div>
        </div>

        <div className="grid md:grid-cols-3 gap-6 mt-8">
          {/* Quick Management */}
          <div className="md:col-span-1 space-y-6">
            <div className="bg-white rounded-2xl p-6 border border-gray-100 shadow-sm">
              <h3 className="font-fredoka text-lg text-text-dark mb-4 flex items-center gap-2">
                <Settings className="w-5 h-5 text-primary" /> Settings
              </h3>
              <div className="space-y-4">
                <div className="flex items-center justify-between p-3 bg-gray-50 rounded-xl">
                  <span className="text-sm font-bold text-text-medium">Daily Limit</span>
                  <div className="flex items-center gap-2">
                    <span className="text-xs text-text-light">30m</span>
                    <div className="w-8 h-4 bg-primary rounded-full relative cursor-pointer">
                      <div className="absolute right-1 top-1 w-2 h-2 bg-white rounded-full" />
                    </div>
                  </div>
                </div>
                <div className="flex items-center justify-between p-3 bg-gray-50 rounded-xl">
                  <span className="text-sm font-bold text-text-medium">Notifications</span>
                  <div className="flex items-center gap-2">
                    <span className="text-xs text-text-light">Off</span>
                    <div className="w-8 h-4 bg-gray-300 rounded-full relative cursor-pointer">
                      <div className="absolute left-1 top-1 w-2 h-2 bg-white rounded-full" />
                    </div>
                  </div>
                </div>
              </div>
            </div>

            <div className="bg-primary-light/10 rounded-2xl p-6 border border-primary/20">
              <h3 className="font-fredoka text-lg text-primary-dark mb-2">Tip for this Week</h3>
              <p className="text-sm text-text-medium leading-relaxed">
                Encourage your child to count actual objects (like pasta or coins) using the "5-complement" rule they learned this week. Real-world application boosts retention!
              </p>
            </div>
          </div>

          {/* detailed Metrics */}
          <div className="md:col-span-2 space-y-6">
            <div className="bg-white rounded-2xl p-6 border border-gray-100 shadow-sm">
              <h3 className="font-fredoka text-xl text-text-dark mb-6 flex items-center gap-2">
                <TrendingUp className="w-5 h-5 text-accent-green" /> Academic Performance
              </h3>
              
        <div className="grid grid-cols-2 gap-4 mb-8">
          <div className="p-4 bg-blue-50 rounded-xl border border-blue-100">
            <span className="text-xs font-bold text-blue-600 uppercase">Current Level</span>
            <div className="text-3xl font-fredoka text-text-dark">{progress?.level || 1}</div>
            <div className="text-xs text-blue-400 mt-1">{progress?.xp || 0} total XP</div>
          </div>
          <div className="p-4 bg-green-50 rounded-xl border border-green-100">
            <span className="text-xs font-bold text-green-600 uppercase">Avg Accuracy</span>
            <div className="text-3xl font-fredoka text-text-dark">{progress?.accuracy || 0}%</div>
            <div className="text-xs text-green-400 mt-1">{progress?.totalProblemsSolved || 0} problems</div>
          </div>
        </div>

        <div className="space-y-3">
          <h4 className="text-sm font-bold text-text-medium mb-2">Recent Lessons</h4>
          {Object.entries(progress?.lessonsProgress || {}).slice(-3).reverse().map(([id, lp]) => (
            <div key={id} className="flex items-center justify-between p-3 border-b border-gray-50 last:border-0">
              <div className="flex items-center gap-3">
                <div className="w-2 h-2 rounded-full bg-accent-green" />
                <span className="text-sm text-text-medium font-medium capitalize">Lesson {id}</span>
              </div>
              <div className="flex items-center gap-4">
                <span className="text-xs text-text-light">Score: {lp.score}%</span>
                <span className="text-xs text-text-light">Time: {lp.bestTime ? `${Math.floor(lp.bestTime / 60)}m ${lp.bestTime % 60}s` : 'N/A'}</span>
              </div>
            </div>
          ))}
          {Object.keys(progress?.lessonsProgress || {}).length === 0 && (
            <div className="text-center py-4 text-text-light text-sm italic">No lessons completed yet.</div>
          )}
        </div>

            </div>

            <div className="bg-red-50 rounded-2xl p-4 border border-red-100 flex items-start gap-3">
              <AlertCircle className="w-5 h-5 text-accent-red flex-shrink-0 mt-0.5" />
              <div className="text-sm text-accent-red font-medium">
                Notice: Your child has hit their daily screen time limit. Encourage them to practice with a physical abacus for the rest of the day!
              </div>
            </div>
          </div>
        </div>

        <div className="bg-white rounded-2xl p-6 border border-gray-100 shadow-sm mt-8">
          <h3 className="font-fredoka text-xl text-text-dark mb-4">Learning Resources</h3>
          <div className="grid sm:grid-cols-2 gap-4">
            <div className="p-4 bg-gray-50 rounded-xl hover:bg-gray-100 cursor-pointer transition-colors">
              <h4 className="font-bold text-text-dark mb-1">Guide to Soroban</h4>
              <p className="text-xs text-text-light">Learn the fundamentals of the Japanese abacus to support your child.</p>
            </div>
            <div 
              onClick={() => window.print()}
              className="p-4 bg-primary/10 border-2 border-primary/20 rounded-xl hover:bg-primary/20 cursor-pointer transition-colors group"
            >
              <div className="flex items-center gap-2 mb-1">
                <Printer className="w-5 h-5 text-primary group-hover:animate-bounce" />
                <h4 className="font-bold text-primary">Printable Worksheets</h4>
              </div>
              <p className="text-xs text-text-medium">Generate random exercises for offline paper practice.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
